name: "Release"

on:
  push:
    branches:
      - main

jobs:
  test_action:
    name: "Release of reusable Maven workflow"
    runs-on: ubuntu-20.04

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3

      - name: "Prepare a draft of release"
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
