name: "Comment"

on:
  pull_request:
    types:
     - opened 
     - reopened 
     - edited 
     - closed 
     - review_requested
  issue_comment:
    types:
      - created
      - edited
  pull_request_review:
    types:
      - submitted
  pull_request_review_comment:
    types:
      - created
      - edited

jobs:
  comment:
    name: "Comment"
    runs-on: ubuntu-20.04
    steps:
      - name: Mention to Slack Actions
        uses: Laurenfrost/mention-to-slack@latest
        with:
          configuration-path: .github/mention-to-slack.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          slack-webhook-url: ${{ secrets.SLACK }}
          icon-url: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          bot-name: ${{github.repository}}
          run-id: ${{ github.run_id }}
          debug-flag: false
          

