name: "Comment"

on:
  pull_request:
    types:
     - opened 
     - reopened 
     - edited 
     - closed 
     - review_requested
  issue_comment:
    types:
      - created
      - edited
  pull_request_review:
    types:
      - submitted
  pull_request_review_comment:
    types:
      - created
      - edited

jobs:
  comment:
    name: "Comment"
    runs-on: ubuntu-20.04
    steps:
    - name: "Print payload"
      run: |
        echo "GH ${{ toJSON(github) }}"
    
    - name: "Prepare message"
      run: |
        echo 'BODY<<EOF' >> $GITHUB_ENV
        echo "${{ github.event.review.body || github.event.comment.body || github.event.pull_request.body }}" | jq -sR . | xargs >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

    - name: "Comment"
      uses: slackapi/slack-github-action@v1
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "TITLE PR ${{ github.event.pull_request.title || github.event.issue.title }}\nPR COMMENT ${{ env.BODY }}"
                }
              }
            ] 
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
