name: "Comment"

on:
  pull_request:

jobs:
  comment:
    name: "Comment"
    runs-on: ubuntu-20.04
    steps:
    
    - name: "Comment"
      uses: slackapi/slack-github-action@v1
      with:
        payload: |
          {
            "text": "COMMENT PR - ${{ github.event.pull_request_review.comment }}\n *Created by:* <${{ github.event.pull_request.user.login }}>",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Comment PR - ${{ job.status }}\n${{ github.event.pull_request_review.comment }} \n *Created by:* <${{ github.event.pull_request.user.login }}>"
                }
              }
            ] 
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
