name: "Comment"

on:
  pull_request:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - converted_to_draft
      - ready_for_review
      - locked
      - unlocked
      - review_requested
      - review_request_removed
      - auto_merge_enabled
      - auto_merge_disabled
  issue_comment:
    types:
      - created
      - edited
      - deleted

jobs:
  comment:
    name: "Comment"
    runs-on: ubuntu-20.04
    steps:
    - name: "Pring payload"
      run: |
        echo "Issue ${{ toJSON(github.event.issue_comment) }}"
        echo "PR  ${{ toJSON(github.event.pull_request) }}"
    
    - name: "Prepare message"
      run: |
        echo 'BODY<<EOF' >> $GITHUB_ENV
        echo "${{ github.event.issue.body }}" | jq -sR . | xargs >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

    - name: "Comment"
      uses: slackapi/slack-github-action@v1
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "TITLE PR ${{ github.event.pull_request.title || github.event.issue.title }} PR COMMENT ${{ env.BODY }}"
                }
              }
            ] 
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
