name: "Comment"

on:
  pull_request:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - converted_to_draft
      - ready_for_review
      - locked
      - unlocked
      - review_requested
      - review_request_removed
      - auto_merge_enabled
      - auto_merge_disabled
  issue_comment:
    types:
      - created
      - edited
      - deleted

jobs:
  comment:
    name: "Comment"
    runs-on: ubuntu-20.04
    steps:
    
    - name: "Comment"
      uses: slackapi/slack-github-action@v1
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "TITLE PR ${{ github.event.pull_request.title }} PR COMMENT ${{ toJSON(github.event.issue_comment.body || github.event.pull_request.body) }}"
                }
              }
            ] 
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
