name: "Greeting on variable day"
on:
  workflow_dispatch
env:
  DAY: Today
jobs:
  job:
    runs-on: ubuntu-latest
    env:
      Say: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Say $Name. Today is $DAY!"
        env:
          Name: John
